global:
  scrape_interval:     15s 

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


remote_write:
  - url: "http://receiver1:10908/api/v1/receive"
  - url: "http://receiver2:10908/api/v1/receive"
